sudo: false
language: node_js
node_js:
  - '12.18.3' # use nodejs v10 LTS
cache: npm
branches:
  only:
    - source_code # build master branch only

script:                       # 在构建阶段需要运行的命令，一条一行，类似的还有 before_script、after_script
  - hexo clean
  - hexo generate             # Hexo 常规命令，执行清理和生成

deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  github-token: $GH_TOKEN
  on:
    branch: source_code
  target_branch: master
  local-dir: public